package com.bank.BSTMS.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * BillInfo
 * @ClassName: BillInfo
 * @Description: BillInfo
 * @author BaiZehong
 * @date 2019年6月27日
 * @since JDK 1.8
 */
public class BillInfo implements Serializable {
    /**
     * Database Column Remarks:
     *   �˵�id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_info.bill_id
     *
     * @mbg.generated
     */
    private Integer billId;

    /**
     * Database Column Remarks:
     *   ���׷���
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_info.card_id_from
     *
     * @mbg.generated
     */
    private Long cardIdFrom;

    /**
     * Database Column Remarks:
     *   ���׽��ܷ�
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_info.card_id_to
     *
     * @mbg.generated
     */
    private Long cardIdTo;

    /**
     * Database Column Remarks:
     *   ��������
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_info.affair_type
     *
     * @mbg.generated
     */
    private String affairType;

    /**
     * Database Column Remarks:
     *   ����ʱ��
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_info.trade_time
     *
     * @mbg.generated
     */
    private Date tradeTime;

    /**
     * Database Column Remarks:
     *   ���׵ص�
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_info.trade_location
     *
     * @mbg.generated
     */
    private String tradeLocation;

    /**
     * Database Column Remarks:
     *   ���׽��
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_info.trade_balance
     *
     * @mbg.generated
     */
    private Double tradeBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bill_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_info.bill_id
     *
     * @return the value of bill_info.bill_id
     *
     * @mbg.generated
     */
    public Integer getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_info.bill_id
     *
     * @param billId the value for bill_info.bill_id
     *
     * @mbg.generated
     */
    public void setBillId(Integer billId) {
        this.billId = billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_info.card_id_from
     *
     * @return the value of bill_info.card_id_from
     *
     * @mbg.generated
     */
    public Long getCardIdFrom() {
        return cardIdFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_info.card_id_from
     *
     * @param cardIdFrom the value for bill_info.card_id_from
     *
     * @mbg.generated
     */
    public void setCardIdFrom(Long cardIdFrom) {
        this.cardIdFrom = cardIdFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_info.card_id_to
     *
     * @return the value of bill_info.card_id_to
     *
     * @mbg.generated
     */
    public Long getCardIdTo() {
        return cardIdTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_info.card_id_to
     *
     * @param cardIdTo the value for bill_info.card_id_to
     *
     * @mbg.generated
     */
    public void setCardIdTo(Long cardIdTo) {
        this.cardIdTo = cardIdTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_info.affair_type
     *
     * @return the value of bill_info.affair_type
     *
     * @mbg.generated
     */
    public String getAffairType() {
        return affairType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_info.affair_type
     *
     * @param affairType the value for bill_info.affair_type
     *
     * @mbg.generated
     */
    public void setAffairType(String affairType) {
        this.affairType = affairType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_info.trade_time
     *
     * @return the value of bill_info.trade_time
     *
     * @mbg.generated
     */
    public Date getTradeTime() {
        return tradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_info.trade_time
     *
     * @param tradeTime the value for bill_info.trade_time
     *
     * @mbg.generated
     */
    public void setTradeTime(Date tradeTime) {
        this.tradeTime = tradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_info.trade_location
     *
     * @return the value of bill_info.trade_location
     *
     * @mbg.generated
     */
    public String getTradeLocation() {
        return tradeLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_info.trade_location
     *
     * @param tradeLocation the value for bill_info.trade_location
     *
     * @mbg.generated
     */
    public void setTradeLocation(String tradeLocation) {
        this.tradeLocation = tradeLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_info.trade_balance
     *
     * @return the value of bill_info.trade_balance
     *
     * @mbg.generated
     */
    public Double getTradeBalance() {
        return tradeBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_info.trade_balance
     *
     * @param tradeBalance the value for bill_info.trade_balance
     *
     * @mbg.generated
     */
    public void setTradeBalance(Double tradeBalance) {
        this.tradeBalance = tradeBalance;
    }
}