package com.bank.BSTMS.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * BusinessInfo
 * @ClassName: BusinessInfo
 * @Description: BusinessInfo
 * @author BaiZehong
 * @date 2019年6月27日
 * @since JDK 1.8
 */
public class BusinessInfo implements Serializable {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_info.business_id
     *
     * @mbg.generated
     */
    private Integer businessId;

    /**
     * Database Column Remarks:
     *   ҵ������
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_info.business_type
     *
     * @mbg.generated
     */
    private String businessType;

    /**
     * Database Column Remarks:
     *   ҵ����Ч����
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_info.business_date
     *
     * @mbg.generated
     */
    private Date businessDate;

    /**
     * Database Column Remarks:
     *   ҵ������
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_info.business_description
     *
     * @mbg.generated
     */
    private String businessDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table business_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_info.business_id
     *
     * @return the value of business_info.business_id
     *
     * @mbg.generated
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_info.business_id
     *
     * @param businessId the value for business_info.business_id
     *
     * @mbg.generated
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_info.business_type
     *
     * @return the value of business_info.business_type
     *
     * @mbg.generated
     */
    public String getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_info.business_type
     *
     * @param businessType the value for business_info.business_type
     *
     * @mbg.generated
     */
    public void setBusinessType(String businessType) {
        this.businessType = businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_info.business_date
     *
     * @return the value of business_info.business_date
     *
     * @mbg.generated
     */
    public Date getBusinessDate() {
        return businessDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_info.business_date
     *
     * @param businessDate the value for business_info.business_date
     *
     * @mbg.generated
     */
    public void setBusinessDate(Date businessDate) {
        this.businessDate = businessDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_info.business_description
     *
     * @return the value of business_info.business_description
     *
     * @mbg.generated
     */
    public String getBusinessDescription() {
        return businessDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_info.business_description
     *
     * @param businessDescription the value for business_info.business_description
     *
     * @mbg.generated
     */
    public void setBusinessDescription(String businessDescription) {
        this.businessDescription = businessDescription;
    }
}