package com.bank.BSTMS.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * CardInfo
 * @ClassName: CardInfo
 * @Description: CardInfo
 * @author BaiZehong
 * @date 2019年6月27日
 * @since JDK 1.8
 */
public class CardInfo implements Serializable {
    /**
     * Database Column Remarks:
     *   ����18λ����
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_info.card_id
     *
     * @mbg.generated
     */
    private Long cardId;

    /**
     * Database Column Remarks:
     *   �û������֤��
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_info.id_numbers
     *
     * @mbg.generated
     */
    private String idNumbers;

    /**
     * Database Column Remarks:
     *   6λ����
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_info.password
     *
     * @mbg.generated
     */
    private Integer password;

    /**
     * Database Column Remarks:
     *   1��ǿ���2���ÿ�
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_info.card_type
     *
     * @mbg.generated
     */
    private Integer cardType;

    /**
     * Database Column Remarks:
     *   �˻����
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_info.account_balance
     *
     * @mbg.generated
     */
    private Double accountBalance;

    /**
     * Database Column Remarks:
     *   ���ÿ���͸֧���
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_info.overdraft_balance
     *
     * @mbg.generated
     */
    private Double overdraftBalance;

    /**
     * Database Column Remarks:
     *   ��Ч��
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_info.end_date
     *
     * @mbg.generated
     */
    private Date endDate;

    /**
     * Database Column Remarks:
     *   ���Ի��ʱ���ʶ��������
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column card_info.exchange_rate_id
     *
     * @mbg.generated
     */
    private Integer exchangeRateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table card_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_info.card_id
     *
     * @return the value of card_info.card_id
     *
     * @mbg.generated
     */
    public Long getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_info.card_id
     *
     * @param cardId the value for card_info.card_id
     *
     * @mbg.generated
     */
    public void setCardId(Long cardId) {
        this.cardId = cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_info.id_numbers
     *
     * @return the value of card_info.id_numbers
     *
     * @mbg.generated
     */
    public String getIdNumbers() {
        return idNumbers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_info.id_numbers
     *
     * @param idNumbers the value for card_info.id_numbers
     *
     * @mbg.generated
     */
    public void setIdNumbers(String idNumbers) {
        this.idNumbers = idNumbers;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_info.password
     *
     * @return the value of card_info.password
     *
     * @mbg.generated
     */
    public Integer getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_info.password
     *
     * @param password the value for card_info.password
     *
     * @mbg.generated
     */
    public void setPassword(Integer password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_info.card_type
     *
     * @return the value of card_info.card_type
     *
     * @mbg.generated
     */
    public Integer getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_info.card_type
     *
     * @param cardType the value for card_info.card_type
     *
     * @mbg.generated
     */
    public void setCardType(Integer cardType) {
        this.cardType = cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_info.account_balance
     *
     * @return the value of card_info.account_balance
     *
     * @mbg.generated
     */
    public Double getAccountBalance() {
        return accountBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_info.account_balance
     *
     * @param accountBalance the value for card_info.account_balance
     *
     * @mbg.generated
     */
    public void setAccountBalance(Double accountBalance) {
        this.accountBalance = accountBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_info.overdraft_balance
     *
     * @return the value of card_info.overdraft_balance
     *
     * @mbg.generated
     */
    public Double getOverdraftBalance() {
        return overdraftBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_info.overdraft_balance
     *
     * @param overdraftBalance the value for card_info.overdraft_balance
     *
     * @mbg.generated
     */
    public void setOverdraftBalance(Double overdraftBalance) {
        this.overdraftBalance = overdraftBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_info.end_date
     *
     * @return the value of card_info.end_date
     *
     * @mbg.generated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_info.end_date
     *
     * @param endDate the value for card_info.end_date
     *
     * @mbg.generated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column card_info.exchange_rate_id
     *
     * @return the value of card_info.exchange_rate_id
     *
     * @mbg.generated
     */
    public Integer getExchangeRateId() {
        return exchangeRateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column card_info.exchange_rate_id
     *
     * @param exchangeRateId the value for card_info.exchange_rate_id
     *
     * @mbg.generated
     */
    public void setExchangeRateId(Integer exchangeRateId) {
        this.exchangeRateId = exchangeRateId;
    }
}