package com.bank.BSTMS.pojo;

import java.io.Serializable;

/**
 * InterestRateInfo
 * @ClassName: InterestRateInfo
 * @Description: InterestRateInfo
 * @author BaiZehong
 * @date 2019年6月27日
 * @since JDK 1.8
 */
public class InterestRateInfo implements Serializable {
    /**
     * Database Column Remarks:
     *   ����id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interest_rate_info.interest_rate_id
     *
     * @mbg.generated
     */
    private Integer interestRateId;

    /**
     * Database Column Remarks:
     *   ��������
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interest_rate_info.interest_rate_type
     *
     * @mbg.generated
     */
    private String interestRateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interest_rate_info.interest_rate
     *
     * @mbg.generated
     */
    private Double interestRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table interest_rate_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interest_rate_info.interest_rate_id
     *
     * @return the value of interest_rate_info.interest_rate_id
     *
     * @mbg.generated
     */
    public Integer getInterestRateId() {
        return interestRateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interest_rate_info.interest_rate_id
     *
     * @param interestRateId the value for interest_rate_info.interest_rate_id
     *
     * @mbg.generated
     */
    public void setInterestRateId(Integer interestRateId) {
        this.interestRateId = interestRateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interest_rate_info.interest_rate_type
     *
     * @return the value of interest_rate_info.interest_rate_type
     *
     * @mbg.generated
     */
    public String getInterestRateType() {
        return interestRateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interest_rate_info.interest_rate_type
     *
     * @param interestRateType the value for interest_rate_info.interest_rate_type
     *
     * @mbg.generated
     */
    public void setInterestRateType(String interestRateType) {
        this.interestRateType = interestRateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interest_rate_info.interest_rate
     *
     * @return the value of interest_rate_info.interest_rate
     *
     * @mbg.generated
     */
    public Double getInterestRate() {
        return interestRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interest_rate_info.interest_rate
     *
     * @param interestRate the value for interest_rate_info.interest_rate
     *
     * @mbg.generated
     */
    public void setInterestRate(Double interestRate) {
        this.interestRate = interestRate;
    }
}